name: Test Workflow Dispatch

on:
  push:
    branches:
      - main
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use current action
        uses: ./
        with:
          parameters: "{a:A,b:B}"
        