name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'First input value'
        required: false
        default: 'default-value-1'
      input2:
        description: 'Second input value'
        required: false
        default: 'default-value-2'

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use current action
        uses: ./
