name: Workflow Call Test
on:
  push:
    branches:
      - main

jobs:
  workflow_call-test:
    uses: ./.github/workflows/called-workflow.yml
    with:
      parameters: ${{ github.event.inputs.parameters }}
